---
# daemon-reload is defined once, in roles/common/handlers/main.yml. See there.

- name: "restart immich.slice"
  listen: "restart immich.slice"
  ansible.builtin.systemd_service:
    name: "immich.slice"
    state: restarted
    scope: user
  failed_when: false

- name: "restart immich.target"
  listen: "restart immich.target"
  ansible.builtin.systemd_service:
    name: "immich.target"
    state: restarted
    scope: user
  failed_when: false

- name: "restart backup-immich.timer"
  listen: "restart backup-immich.timer"
  ansible.builtin.systemd_service:
    name: "backup-immich.timer"
    state: restarted
    scope: user
  failed_when: false

- name: "restart immich-machine-learning.service"
  listen: "restart immich-machine-learning.service"
  ansible.builtin.systemd_service:
    name: "immich-machine-learning.service"
    state: restarted
    scope: user
  failed_when: false

- name: "restart immich-postgres.service"
  listen: "restart immich-postgres.service"
  ansible.builtin.systemd_service:
    name: "immich-postgres.service"
    state: restarted
    scope: user
  failed_when: false

- name: "restart immich-redis.service"
  listen: "restart immich-redis.service"
  ansible.builtin.systemd_service:
    name: "immich-redis.service"
    state: restarted
    scope: user
  failed_when: false

- name: "restart immich-server.service"
  listen: "restart immich-server.service"
  ansible.builtin.systemd_service:
    name: "immich-server.service"
    state: restarted
    scope: user
  failed_when: false
