repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.3.8
    values:
      - provider: pihole
      - policy: upsert-only
      - txtOwnerId: 'pihole-k3s'
      - registry: noop
      - pihole:
          server: http://pihole-web.pihole-system.svc.cluster.local
      - extraEnvVars:
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pihole-password
                key: password
      - serviceAccount:
          create: true
          name: 'external-dns'
      - ingressClassFilters:
          - traefik
      - resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
