repositories:
  - name: intel
    url: https://intel.github.io/helm-charts/
releases:
  - name: dp-operator
    namespace: inteldeviceplugins-system
    chart: intel/intel-device-plugins-operator
    version: 0.30.0
