repositories:
  - name: longhorn
    url: https://charts.longhorn.io
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1
    values:
      - persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
      - csi:
          attacherReplicaCount: 3
          provisionerReplicaCount: 3
          snapshotterReplicaCount: 3
      - longhornUI:
          replicas: 1
      - ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: 'true'
            traefik.ingress.kubernetes.io/router.middlewares: default-default-headers@kubernetescrd
            cert-manager.io/cluster-issuer: letsencrypt-production
          host: longhorn.cavestri.net
          path: /
          tls: true
          tlsSecret: longhorn-cavestri-net-tls
