repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes
releases:
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - adlists: {}
      - adminPassword: admin
      - doh:
          enabled: true
          name: cloudflared
          probes:
            liveness:
              enabled: true
              failureThreshold: 10
              initialDelaySeconds: 60
              probe: {'exec': {'command': ['nslookup', '-po=5053', 'cloudflare.com', '127.0.0.1']}}
              timeoutSeconds: 5
      - hostname: pihole-k3s
      - persistentVolumeClaim:
          enabled: true
          size: 512Mi
      - probes:
          liveness:
            failureThreshold: 10
            initialDelaySeconds: 60
            timeoutSeconds: 5
            type: httpGet
          readiness:
            enabled: true
            failureThreshold: 3
            initialDelaySeconds: 60
            port: http
            timeoutSeconds: 5
      - replicaCount: 1
      - resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - serviceDhcp:
          loadBalancerIP: 192.168.1.250
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
      - serviceDns:
          loadBalancerIP: 192.168.1.250
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
          type: LoadBalancer
      - serviceWeb:
          type: ClusterIP
      - ingress:
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: 'true'
            cert-manager.io/cluster-issuer: letsencrypt-production
            traefik.ingress.kubernetes.io/router.middlewares: default-default-headers@kubernetescrd
          enabled: true
          hosts:
            - pihole.cavestri.net
          path: /
          tls:
            - secretName: pihole-cavestri-net-tls
              hosts:
                - pihole.cavestri.net
      - strategyType: RollingUpdate
      - virtualHost: pihole.cavestri.net
