services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.5
    container_name: homepage
    environment:
      PUID: 0
      PGID: 0
    volumes:
      - ${CONFIG_PATH}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${HOST}`)
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.tls.certresolver=${RESOLVER}
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.http.routers.homepage.middlewares=authentik@file
networks:
  proxy:
    external: true
