services:
  cloudflare-ddns:
    container_name: cloudflareddns
    image: favonia/cloudflare-ddns:1.11.0
    network_mode: host
    restart: always
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - CF_API_TOKEN=${CF_API}
      - DOMAINS=${DOMAINS}
      - PROXIED=true
networks: {}
