services:
  vaultwarden:
    image: vaultwarden/server:1.32.2-alpine
    container_name: vaultwarden
    environment:
      WEBSOCKET_ENABLED: "true"
    volumes:
      - ${DATA_PATH}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${HOST}`)
      - traefik.http.routers.vaultwarden.entrypoints=https
      - traefik.http.routers.vaultwarden.tls.certresolver=${RESOLVER}
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
