<?php
$CONFIG = array (
  'datadirectory' => '/data',
  'instanceid' => 'AUTOGENERATED',
  'passwordsalt' => 'YOUR-PASS',
  'secret' => 'YOUR-SECRET',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'nextcloud.example.com',
  'overwrite.cli.url' => 'https://nextcloud.example.com',
  'trusted_proxies' =>
  array (
    0 => '172.22.0.0/24',
  ),
  'trusted_domains' =>
  array (
    0 => 'nextcloud.example.com',
  ),
  'wopi_allowlist' =>
  array (
    0 => 'collabora.example.com',
  ),
  'dbtype' => 'mysql',
  'version' => '29.0.0.19',
  'overwrite.cli.url' => 'http://nextcloud.example.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'mariadb-nextcloud:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'YOUR-DB-USER',
  'dbpassword' => 'YOUR-DB-PASS',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  #'memcache.locking' => '\\OC\\Memcache\\APCu',
  #'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => array(
    'host' => 'nextcloud-redis',
    'port' => 6379,
  ),
  'filelocking.enabled' => true,
  'upgrade.disable-web' => true,
  'maintenance' => false,
  'allow_local_remote_servers' => true,
  'default_language' => 'it', # Set your language
  'default_locale' => 'it_IT', # Set your locale
  'default_phone_region' => 'IT', # Set your phone region
  'default_timezone' => 'Europe/Rome', # Set your timezone
  'maintenance_window_start' => '02:00:00',
  'opcache.enable' => '1',
  'opcache.enable_cli' => '1',
  'opcache.interned_strings_buffer' => '8',
  'opcache.max_accelerated_files' => '10000',
  'opcache.memory_consumption' => '128',
  'opcache.save_comments' => '1',
  'opcache.revalidate_freq' => '60',
  'opcache.jit' => '1255',
  'opcache.jit_buffer_size' => '128M',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\GIF',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\XBitmap',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\MP4',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\PDF',
  ),
);

