---
common_files:
  - src: "infrastructure.target.j2"
    dest: "~/.config/systemd/user/infrastructure.target"
    notify: ['restart infrastructure.target']
    mode: "0644"
  - src: "media.target.j2"
    dest: "~/.config/systemd/user/media.target"
    notify: ['restart media.target']
    mode: "0644"
  - src: "notify-failure@.service.j2"
    dest: "~/.config/systemd/user/notify-failure@.service"
    notify: []
    mode: "0644"
  - src: "notify-recovery@.service.j2"
    dest: "~/.config/systemd/user/notify-recovery@.service"
    notify: []
    mode: "0644"
  - src: "podman.service.d__loglevel.conf.j2"
    dest: "~/.config/systemd/user/podman.service.d/loglevel.conf"
    notify: []
    mode: "0644"
  - src: "podman-auto-update.service.d__override.conf.j2"
    dest: "~/.config/systemd/user/podman-auto-update.service.d/override.conf"
    notify: []
    mode: "0644"
  - src: "homepage.container.j2"
    dest: "~/.config/containers/systemd/homepage.container"
    notify: ['restart homepage.service']
    mode: "0644"
  - src: "homepage.env.j2"
    dest: "~/.config/homepage/homepage.env"
    notify: ['restart homepage.service']
    mode: "0600"
