services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.11
    container_name: jellyfin
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/media
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${HOST}`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls.certresolver=${RESOLVER}
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: unless-stopped
networks:
  proxy:
    external: true
