services:
  cloudflare-ddns:
    container_name: cloudflareddns
    image: favonia/cloudflare-ddns:1.13.2
    network_mode: host
    restart: always
    user: "1000:1000"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - CF_API_TOKEN=${CF_API}
      - DOMAINS=${DOMAINS}
      - PROXIED=true
networks: {}
