services:
  jellyfin:
    image: jellyfin/jellyfin:2024050902
    container_name: jellyfin
    volumes:
      - ${CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/media
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`${HOST}`)
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.tls.certresolver=${RESOLVER}
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: unless-stopped
networks:
  proxy:
    external: true
