services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.1.42
    volumes:
      - ${OLLAMA_PATH}:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.3.2
    container_name: open-webui
    volumes:
      - ${OPENWEBUI_PATH}:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_NAME: ${WEBUI_NAME}
      ENV: prod
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
networks: {}
