---
office_files:
  - src: "office.network.j2"
    dest: "~/.config/containers/systemd/office.network"
    notify: []
    mode: "0644"
  - src: "office.slice.j2"
    dest: "~/.config/systemd/user/office.slice"
    notify: ['restart office.slice']
    mode: "0644"
  - src: "office.target.j2"
    dest: "~/.config/systemd/user/office.target"
    notify: ['restart office.target']
    mode: "0644"
  - src: "backup-office.service.j2"
    dest: "~/.config/systemd/user/backup-office.service"
    notify: []
    mode: "0644"
  - src: "backup-office.timer.j2"
    dest: "~/.config/systemd/user/backup-office.timer"
    notify: ['restart backup-office.timer']
    mode: "0644"
  - src: "freshrss.container.j2"
    dest: "~/.config/containers/systemd/freshrss.container"
    notify: ['restart freshrss.service']
    mode: "0644"
  - src: "vaultwarden.container.j2"
    dest: "~/.config/containers/systemd/vaultwarden.container"
    notify: ['restart vaultwarden.service']
    mode: "0644"
  - src: "freshrss.env.j2"
    dest: "~/.config/office/freshrss.env"
    notify: ['restart freshrss.service']
    mode: "0600"
  - src: "vaultwarden.env.j2"
    dest: "~/.config/office/vaultwarden.env"
    notify: ['restart vaultwarden.service']
    mode: "0600"
