---
immich_slice:
  memory_max: "8G"
  memory_swap_max: "0"
  cpu_quota: "800%"

immich_postgres:
  user: "immich"
  db: "immich"

immich:
  db_hostname: "immich-postgres"
  db_username: "immich"
  db_database_name: "immich"
  redis_hostname: "immich-redis"
  gomaxprocs: "4"
  omp_num_threads: "4"
  nvidia_visible_devices: "all"
  nvidia_driver_capabilities: "compute,video,utility"
