---
media_jellyfin_files:
  - src: "jellyfin.network.j2"
    dest: "~/.config/containers/systemd/jellyfin.network"
    notify: []
    mode: "0644"
  - src: "jellyfin.slice.j2"
    dest: "~/.config/systemd/user/jellyfin.slice"
    notify: ['restart jellyfin.slice']
    mode: "0644"
  - src: "jellyfin.target.j2"
    dest: "~/.config/systemd/user/jellyfin.target"
    notify: ['restart jellyfin.target']
    mode: "0644"
  - src: "jellyfin.container.j2"
    dest: "~/.config/containers/systemd/jellyfin.container"
    notify: ['restart jellyfin.service']
    mode: "0644"
  - src: "jellyfin-exporter.container.j2"
    dest: "~/.config/containers/systemd/jellyfin-exporter.container"
    notify: ['restart jellyfin-exporter.service']
    mode: "0644"
  - src: "backup-jellyfin.service.j2"
    dest: "~/.config/systemd/user/backup-jellyfin.service"
    notify: []
    mode: "0644"
  - src: "backup-jellyfin.timer.j2"
    dest: "~/.config/systemd/user/backup-jellyfin.timer"
    notify: ['restart backup-jellyfin.timer']
    mode: "0644"
  - src: "update-egr.service.j2"
    dest: "~/.config/systemd/user/update-egr.service"
    notify: []
    mode: "0644"
  - src: "update-egr.timer.j2"
    dest: "~/.config/systemd/user/update-egr.timer"
    notify: ['restart update-egr.timer']
    mode: "0644"
  - src: "jellyfin-exporter.env.j2"
    dest: "~/.config/media/jellyfin/jellyfin-exporter.env"
    notify: ['restart jellyfin-exporter.service']
    mode: "0600"
  - src: "jellyfin.env.j2"
    dest: "~/.config/media/jellyfin/jellyfin.env"
    notify: ['restart jellyfin.service']
    mode: "0600"
