---
# daemon-reload is defined once, in roles/common/handlers/main.yml. See there.

- name: "restart netcore.slice"
  listen: "restart netcore.slice"
  ansible.builtin.systemd_service:
    name: "netcore.slice"
    state: restarted
    scope: user
  failed_when: false

- name: "restart netcore.target"
  listen: "restart netcore.target"
  ansible.builtin.systemd_service:
    name: "netcore.target"
    state: restarted
    scope: user
  failed_when: false

- name: "restart backup-netcore.timer"
  listen: "restart backup-netcore.timer"
  ansible.builtin.systemd_service:
    name: "backup-netcore.timer"
    state: restarted
    scope: user
  failed_when: false

- name: "restart ddns-updater.service"
  listen: "restart ddns-updater.service"
  ansible.builtin.systemd_service:
    name: "ddns-updater.service"
    state: restarted
    scope: user
  failed_when: false

- name: "restart pihole.service"
  listen: "restart pihole.service"
  ansible.builtin.systemd_service:
    name: "pihole.service"
    state: restarted
    scope: user
  failed_when: false
