---
auth_files:
  - src: "auth.slice.j2"
    dest: "~/.config/systemd/user/auth.slice"
    notify: ['restart auth.slice']
    mode: "0644"
  - src: "auth.target.j2"
    dest: "~/.config/systemd/user/auth.target"
    notify: ['restart auth.target']
    mode: "0644"
  - src: "authentik.network.j2"
    dest: "~/.config/containers/systemd/authentik.network"
    notify: []
    mode: "0644"
  - src: "authentik-postgres.container.j2"
    dest: "~/.config/containers/systemd/authentik-postgres.container"
    notify: ['restart authentik-postgres.service']
    mode: "0644"
  - src: "authentik-server.container.j2"
    dest: "~/.config/containers/systemd/authentik-server.container"
    notify: ['restart authentik-server.service']
    mode: "0644"
  - src: "authentik-worker.container.j2"
    dest: "~/.config/containers/systemd/authentik-worker.container"
    notify: ['restart authentik-worker.service']
    mode: "0644"
  - src: "backup-auth.service.j2"
    dest: "~/.config/systemd/user/backup-auth.service"
    notify: []
    mode: "0644"
  - src: "backup-auth.timer.j2"
    dest: "~/.config/systemd/user/backup-auth.timer"
    notify: ['restart backup-auth.timer']
    mode: "0644"
  - src: "authentik.env.j2"
    dest: "~/.config/infrastructure/auth/authentik/authentik.env"
    notify: ['restart authentik-postgres.service', 'restart authentik-server.service', 'restart authentik-worker.service']
    mode: "0600"
